build: 
	javac -g src/PoduriObj.java src/MyScanner.java src/Poduri.java  src/Adrese.java src/Lego.java
run-p1:	
	java -cp src/ Poduri
run-p2:
	java -cp src/ Adrese
run-p3:
	java -cp src/ Lego
clean:
	rm -rf src/*.class