build: 
	javac -g src/CryptoObj.java src/MyScanner.java src/Crypto.java src/Valley.java src/Stocks.java src/RidgeObj.java src/Ridge.java
run-p1:	
	java -cp src/ Crypto
run-p2:
	java -cp src/ Stocks
run-p3:
	java -cp src/ Valley 
run-p4:
	java -cp src/ Ridge
clean:
	rm -rf src/*.class